// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1

package db

import (
	"database/sql"
	"time"
)

type Partido struct {
	IDPartido          int32          `json:"id_partido"`
	Fecha              time.Time      `json:"fecha"`
	TipoCancha         int32          `json:"tipo_cancha"`
	Rival              string         `json:"rival"`
	Resultado          string         `json:"resultado"`
	Posicion           sql.NullString `json:"posicion"`
	GolesPropios       int32          `json:"goles_propios"`
	AsistenciasPropias int32          `json:"asistencias_propias"`
	PuntajePropio      int32          `json:"puntaje_propio"`
}
