// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1
// source: users.sql

package db

import (
	"context"
	"database/sql"
	"time"
)

const createPartido = `-- name: CreatePartido :exec
INSERT INTO partido (
    fecha, tipo_cancha, rival, resultado, 
    posicion, goles_propios, asistencias_propias, puntaje_propio
) VALUES (
    $1, $2, $3, $4, $5, $6, $7, $8
)
`

type CreatePartidoParams struct {
	Fecha              time.Time      `json:"fecha"`
	TipoCancha         int32          `json:"tipo_cancha"`
	Rival              string         `json:"rival"`
	Resultado          string         `json:"resultado"`
	Posicion           sql.NullString `json:"posicion"`
	GolesPropios       int32          `json:"goles_propios"`
	AsistenciasPropias int32          `json:"asistencias_propias"`
	PuntajePropio      int32          `json:"puntaje_propio"`
}

func (q *Queries) CreatePartido(ctx context.Context, arg CreatePartidoParams) error {
	_, err := q.db.ExecContext(ctx, createPartido,
		arg.Fecha,
		arg.TipoCancha,
		arg.Rival,
		arg.Resultado,
		arg.Posicion,
		arg.GolesPropios,
		arg.AsistenciasPropias,
		arg.PuntajePropio,
	)
	return err
}

const deletePartido = `-- name: DeletePartido :exec
DELETE FROM partido
WHERE id_partido = $1
`

func (q *Queries) DeletePartido(ctx context.Context, idPartido int32) error {
	_, err := q.db.ExecContext(ctx, deletePartido, idPartido)
	return err
}

const getPartido = `-- name: GetPartido :one
SELECT id_partido, fecha, tipo_cancha, rival, resultado, posicion, goles_propios, asistencias_propias, puntaje_propio 
FROM partido
WHERE id_partido = $1
`

func (q *Queries) GetPartido(ctx context.Context, idPartido int32) (Partido, error) {
	row := q.db.QueryRowContext(ctx, getPartido, idPartido)
	var i Partido
	err := row.Scan(
		&i.IDPartido,
		&i.Fecha,
		&i.TipoCancha,
		&i.Rival,
		&i.Resultado,
		&i.Posicion,
		&i.GolesPropios,
		&i.AsistenciasPropias,
		&i.PuntajePropio,
	)
	return i, err
}

const listPartidos = `-- name: ListPartidos :many
SELECT id_partido, fecha, tipo_cancha, rival, resultado, posicion, goles_propios, asistencias_propias, puntaje_propio 
FROM partido
ORDER BY fecha DESC
`

func (q *Queries) ListPartidos(ctx context.Context) ([]Partido, error) {
	rows, err := q.db.QueryContext(ctx, listPartidos)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []Partido
	for rows.Next() {
		var i Partido
		if err := rows.Scan(
			&i.IDPartido,
			&i.Fecha,
			&i.TipoCancha,
			&i.Rival,
			&i.Resultado,
			&i.Posicion,
			&i.GolesPropios,
			&i.AsistenciasPropias,
			&i.PuntajePropio,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const updatePartido = `-- name: UpdatePartido :exec
UPDATE partido
SET 
    fecha = $2,
    tipo_cancha = $3,
    rival = $4,
    resultado = $5,
    posicion = $6,
    goles_propios = $7,
    asistencias_propias = $8,
    puntaje_propio = $9
WHERE id_partido = $1
`

type UpdatePartidoParams struct {
	IDPartido          int32          `json:"id_partido"`
	Fecha              time.Time      `json:"fecha"`
	TipoCancha         int32          `json:"tipo_cancha"`
	Rival              string         `json:"rival"`
	Resultado          string         `json:"resultado"`
	Posicion           sql.NullString `json:"posicion"`
	GolesPropios       int32          `json:"goles_propios"`
	AsistenciasPropias int32          `json:"asistencias_propias"`
	PuntajePropio      int32          `json:"puntaje_propio"`
}

func (q *Queries) UpdatePartido(ctx context.Context, arg UpdatePartidoParams) error {
	_, err := q.db.ExecContext(ctx, updatePartido,
		arg.IDPartido,
		arg.Fecha,
		arg.TipoCancha,
		arg.Rival,
		arg.Resultado,
		arg.Posicion,
		arg.GolesPropios,
		arg.AsistenciasPropias,
		arg.PuntajePropio,
	)
	return err
}
